version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: chainlite-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chainlite
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017" # optional: expose for local tools
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chainlite-api
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  mongo_data: